runtime: java
api_version: '1.0'
env: flex
threadsafe: true
handlers:
  - url: /.*
    script: thsi field is required but ignored.
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.5