apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: employee-management
  name: employee-management
  namespace: search-component
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: employee-management
  template:
    metadata:
      labels:
        run: employee-management
    spec:
      containers:
        - image: us.gcr.io/javacourse2022-19-oct/employee-management:develop-1
          imagePullPolicy: "Always"
          name: employee-management
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: PROJECT_ID
              value: javacourse2022-19-oct